### ISSUE TITLE
Android studio does not pick up generated source

### ISSUE THREAD

**Issue by jdpatterson** [tbroyer/gradle-apt-plugin#1]
Running my build from the command line works.  Running the build from within Android Studio works.  The editor shows the generated DaggerXxxx classes as missing.  The build/generated/source/apt directory is not in the generated .iml file.  When I add an item to sourceSets.main.java.srcDir it does get picked up.

**Comment by tbroyer** [comment]
Did you `apply plugin: "idea"` to your project?
IntelliJ IDEA (and derivatives such as Android Studio) won't be configured if that's not the case.

**Comment by jdpatterson** [comment]
Great thanks that fixed it!  I incorrectly assumed that Android Studio replaced IDEAs build system so that plugin would not apply.
