### ISSUE TITLE
Java 6 support

### ISSUE THREAD

**Issue by jawnsy** [tbroyer/gradle-apt-plugin#11]
Hi,

Apparently this plugin doesn't run on Java 6 -- would it be possible to fix this, perhaps by building with Java 6 source/target compatibility?  I haven't looked at the source, so I don't know whether some newer Java 7 capabilities are required.

This is useful for libraries, which often have to support ancient Java versions. I realize that it's not a good idea to run with a Java version that isn't supported by Oracle anymore in its official releases, but if it's not too much trouble to add support, it might be useful to some people.  Keep in mind that Oracle and IBM both provide commercial support for older versions (including Java 6), so it's not completely End of Life.

> java.lang.UnsupportedClassVersionError: net/ltgt/gradle/apt/AptPlugin : Unsupported major.minor version 51.0

https://travis-ci.org/jawnsy/openshift-client/jobs/91176388

Thanks for your consideration,

Jonathan

**Comment by tbroyer** [comment]
Plugin classes themselves don't require Java 7. Nebula Test however does, so I'd have to migrate to the new [Gradle TestKit](https://docs.gradle.org/current/userguide/test_kit.html). Either that or just compiling with `sourceCompatibility` and `targetCompatibility` but without the appropriate `bootclasspath` so without any guarantee that it'd _actually_ work in a Java 6 VM (even though the risk is low).
Pull request welcome.

That said, your openshift-client uses OkHttp, which is also built against Java 7.

**Comment by jawnsy** [comment]
Thanks for the quick reply :)

Ugh, bummer that OkHttp requires Java 7. I guess the easiest solution is just to require Java 7, which isn't so bad, seeing as how the latest few versions of Eclipse (4.4 and 4.5) also require Java 7.

Perhaps a better way to resolve this is just by adding a statement to your README indicating that Java 7 is required?  I guess the [market share](https://plumbr.eu/blog/java/java-version-statistics-2015-edition) may be sufficiently low now?

**Comment by tbroyer** [comment]
I think nowadays people targeting Java 6 need to double or triple-check their dependencies anyway, most people using Java 7 or Java 8. Just one or two weeks ago, while releasing a new library, I was wondering whether to target Java 7 or Java 8. Many tools and libraries are switching to Java 8 already: http://www.jooq.org/notes#3.7.0, https://joel-costigliola.github.io/assertj/assertj-core-news.html#assertj-core-3.2.0, https://github.com/google/error-prone/issues/369#issuecomment-151932863, and many have switched to Java 7 (not always without consequences): https://jenkins-ci.org/changelog-stable#v1.625.1

BTW, you can still run Gradle with Java 7 or 8 and have the `compileJava` task [use a JDK 6](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/compile/ForkOptions.html#setExecutable%28java.lang.String%29) and/or configure it with a Java 6 [`bootclasspath`](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.CompileOptions.html#org.gradle.api.tasks.compile.CompileOptions:bootClasspath) and [`extdirs`](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.CompileOptions.html#org.gradle.api.tasks.compile.CompileOptions:extensionDirs) for proper [cross-compilation](https://docs.oracle.com/javase/8/docs/technotes/tools/unix/javac.html#BHCIJIEG) (pending support for Java toolchains in Gradle)
