### ISSUE TITLE
.factorypath file generation not easy to isolate

### ISSUE THREAD

**Issue by juckele** [tbroyer/gradle-apt-plugin#13]
`.classpath` and `.factorypath` files serve very similar roles, and both should be autogenerated by a Gradle user. `.settings/` files can store information which a user wishes to version control (such as auto formatting).

If a user adds a new dependency to the gradle build script, they should be able to update the `.classpath` and `.factorypath` files without overwriting the `.settings/` files. Currently, running `gradle eclipseClasspath` will update the `.classpath` file without touching the `.settings/` files, but it doesn't cause the `.factorypath` file to update.

Either `eclipseClasspath` should also update the `.factorypath` file, or an `eclipseFactorypath` task should be added.

**Comment by tbroyer** [comment]
Ah, you're right! In the spirit of the Eclipse plugins, I think there should be specific tasks for `.settings/org.eclipse.jdt.apt.core.prefs` and `.factorypath` files and have the `eclipse` task depend on them.
Currently the files are created during the `eclipseJdt` task, and (I believe) aren't cleaned by `cleanEclipseJdt`.

**Comment by tbroyer** [comment]
Should be fixed by 50d11631922e0de7c17797bd7498cf8d0458fdf5

I'll cut a release soon so you can test the changes and provide feedback.

**Comment by tbroyer** [comment]
I published version 0.5 to the Gradle Plugins Portal if you want to take a look.

**Comment by juckele** [comment]
Works like a charm. Thanks.
