### ISSUE TITLE
Dependency resolution for compile classpath doesn't use latest versions

### ISSUE THREAD

**Issue by sherter** [tbroyer/gradle-apt-plugin#22]
Transitive dependencies of `compileOnly` dependencies don't seem to be resolved properly against other compile time dependencies. When the `compileOnly` configuration contains a newer version of a library, then this newer version is not used in the `compileClasspath`.

See this [example](https://github.com/sherter/google-java-format-gradle-plugin/tree/e07ac245bd7e508e7cd0eed2c2a123d0a84927b5) and the [output](https://travis-ci.org/sherter/google-java-format-gradle-plugin/builds/122502246) on travis. It uses `dagger 2.3`, which declares a dependency on `guava 19.0`, but `guava-jdk5-17.0.jar` ends up on the `compileClasspath` (which probably comes from gradle).

Also see related [AOSP issue](https://code.google.com/p/android/issues/detail?id=206407).

**Comment by tbroyer** [comment]
There are 2 problems here:

 * google-java-format has a packaging issue and bundles Guava 18, which then conflicts with Dagger's need for Guava 19; see google/dagger#356
 * as far as version conflict mediation/resolution is concerned, `com.google.guava:guava-jdk5` and `com.google.guava:guava` are 2 distinct things, so it's OK to have both on the classpath. If you want one to _override_ the other, use Gradle facilities (many to choose from, see https://docs.gradle.org/2.11/userguide/dependency_management.html#N12425) to replace one with the other, or possibly simply exclude one.

**Comment by tbroyer** [comment]
Oh, BTW, the scenario you describe is taken care of: see https://github.com/tbroyer/gradle-apt-plugin/blob/master/src/test/groovy/net/ltgt/gradle/apt/AptPluginSpec.groovy#L113
The `'annotations:compile:1.0'` used as `compileOnly` depends on `'leaf:compile:2.0'`, whereas `'compile:compile:1.0'` used as `compile` depends on `'leaf:compile:1.0'`.
At https://github.com/tbroyer/gradle-apt-plugin/blob/master/src/test/groovy/net/ltgt/gradle/apt/AptPluginSpec.groovy#L160-L161 it is tested that `'leaf:compile:2.0'` is used in the `compileOnly` configuration (and not `'leaf:compile:1.0'`)
At https://github.com/tbroyer/gradle-apt-plugin/blob/master/src/test/groovy/net/ltgt/gradle/apt/AptPluginSpec.groovy#L150 it is tested that the `compileClasspath` is equal to the `compileOnly` configuration.
And at https://github.com/tbroyer/gradle-apt-plugin/blob/master/src/test/groovy/net/ltgt/gradle/apt/AptPluginSpec.groovy#L152 it is tested that the `compileJava` classpath uses that `compileClasspath`

**Comment by sherter** [comment]
> - google-java-format has a packaging issue and bundles Guava 18, which then conflicts with Dagger's need for Guava 19; see google/dagger#356

I don't see how this has anything to do with this? I don't use `google-java-format` as a dependency anywhere (at least not statically) ...

> - as far as version conflict mediation/resolution is concerned, com.google.guava:guava-jdk5 and com.google.guava:guava are 2 distinct things, so it's OK to have both on the classpath. If you want one to override the other, use Gradle facilities (many to choose from, see https://docs.gradle.org/2.11/userguide/dependency_management.html#N12425) to replace one with the other, or possibly simply exclude one.

Thanks for this suggestion, have to look into it. However, the jdk5 version is a distinct thing, why doesn't the other appear at all on the classpath?

**Comment by tbroyer** [comment]
> > * google-java-format has a packaging issue and bundles Guava 18, which then conflicts with Dagger's need for Guava 19; see google/dagger#356
> 
> I don't see how this has anything to do with this? I don't use google-java-format as a dependency anywhere (at least not statically) ...

Dagger 2.3 bundles google-java-format, and as result bundles Guava 18 (while depending on Guava 19, and needing Guava 19 APIs); see google/dagger#356, which exhibits the exact same error as you're seeing.

**Comment by sherter** [comment]
Oh, I see.. thanks :wink:
