### ISSUE TITLE
Mention in the README that the aptTest config does not inherit from apt

### ISSUE THREAD

**Issue by ddimtirov** [tbroyer/gradle-apt-plugin#25]
This caused some confusion as we tried to implement Dagger modules for integration testing and while the build was passing in IDEA, it was failing in Gradle.

**Comment by tbroyer** [comment]
Well, it doesn't say that `testApt` extends `apt` (when it says `compileOnly` extends `compile`, for example); do you think it should explicitly say _“`aptTest` (does **not** extend `apt`)”_ ?

**Comment by ddimtirov** [comment]
Well test extends compile, testRuntime extends runtime, it took me to go to the plugin source to realize that testApt does not extend apt.

It is likely to confuse other people too.

**Comment by tbroyer** [comment]
Well, `compileTest` extends `compile`, but `testCompileOnly` does not extend `compileOnly` either. The day you need your `apt` configuration to **not** apply to `compileTestJava`, it feels natural that `testApt` does not extend `apt` ;-)

Will add an explicit note in the README though.

**Comment by ddimtirov** [comment]
I understand the reasoning and don't mind the behavior, it was just a but counterintuitive. An explicit mention in the readme should be enough. 

You may also provide the tip that one can do `testApt configurations.apt` in the `dependencies` section to make the main processors available in the test claaaoatg.

**Comment by tbroyer** [comment]
Fixed by 967da74741dec4d3b416d1ff5f937bd6bd67bf30
