### ISSUE TITLE
Generated source is not getting added to my android studio java library project's sourceSet

### ISSUE THREAD

**Issue by bhargavms** [tbroyer/gradle-apt-plugin#26]
![selection_026](https://cloud.githubusercontent.com/assets/10993824/16228201/3ec26394-37d3-11e6-870d-c86f4ea38aeb.png)

As you can see from the screenshot the generated classes are not in my source set and hence the error icon next the class files

**Comment by tbroyer** [comment]
I have no idea why you define an `apt` sourceSet, but this looks a lot like #24, thus closing as duplicate.
See also https://github.com/tbroyer/gradle-apt-plugin/pull/4#issuecomment-221650196

**Comment by bhargavms** [comment]
I was trying to add the generated source to my source set, my IDE is not detecting these sources, anyway even if I were to remove it (which is by default) it doesnt work

**Comment by bhargavms** [comment]
Alright you need to `apply plugin: "idea"` for it to work goddamit!
