### ISSUE TITLE
Broken with Gradle 3.0

### ISSUE THREAD

**Issue by ddimtirov** [tbroyer/gradle-apt-plugin#27]
The following line was logging a deprecation warning in Gradle 2.14 and throws missing property exception in 3.0-M2:

https://github.com/tbroyer/gradle-apt-plugin/blob/master/src/main/groovy/net/ltgt/gradle/apt/AptPlugin.groovy#L120

**Comment by tbroyer** [comment]
Thanks for the report. It appears `noExportConfigurations` was not needed at all for all this time. I blame cargo-cult.
This is fixed in a1d2d9146c87b7d0963266303d31d6c1d77e35ff; I'll cut a new release soon.

**Comment by tbroyer** [comment]
FWIW, version 0.7 has been released.

**Comment by ddimtirov** [comment]
Thanks, will try it out soon
