### ISSUE TITLE
Support of arguments 

### ISSUE THREAD

**Issue by aminelaadhari** [tbroyer/gradle-apt-plugin#28]
Some annotation processor may require to pass custom arguments. Is it possible to apt configuration section to the build.gradle file like the android plugin ?
https://bitbucket.org/hvisser/android-apt

> Passing processor arguments
Some annotation processor may require to pass custom arguments, you can use apt.arguments for that purpose. For instance for AndroidAnnotations you can use the following configuration:
```
apt {
    arguments {
            resourcePackageName android.defaultConfig.applicationId
            androidManifestFile variant.outputs[0]?.processResources?.manifestFile
    }
}
```

**Comment by tbroyer** [comment]
I'm not a fan of this in android-apt.

Gradle has no similar mean for setting any compiler argument globally, so there's no reason to add one for annotation processor arguments. Plus, it's really easy to do it "manually":
```gradle
tasks.withType(JavaCompile) {
  options.compilerArgs += [ "-Afoo=bar", "-Abaz=${quux}" ]
}
```

I know that the experimental experimental new Android Gradle plugin (2.2 alpha) has an `annotationProcessorArguments` similar to android-apt, but it is inside a `javaCompileOptions` (that, in addition, is per-flavor).

So I'm not keen in adding this to this plugin. I _may_ add something at the `JavaCompile` task level so you don't have to properly "format" the key-values with `-A` prefix and `=` separator, but not globally like android-apt does it; that does not feel "Gradle-native" to me.

**Comment by aminelaadhari** [comment]
Fair enough, thanks for the explanation.
