### ISSUE TITLE
Support for joint compilation with Scala

### ISSUE THREAD

**Issue by tomrozb** [tbroyer/gradle-apt-plugin#3]
Is it possible to provide support for joint compilation with Scala sources?

I'm using Scala classes in Java classes. To compile such combination I need below configuration:

```
sourceSets.main {
  // Joint compilation with Scala sources
  scala.srcDir "src/main/java"
  java.srcDirs = []
}
```

This breaks code generation because this plugin is based on `compileJava` task. All the code is compiled by `compileScala` task in my case.

**Comment by tbroyer** [comment]
I know nothing about Scala (and its different compilers supported by Gradle), so I'm afraid you'd have to contribute the fix. At a minimum, if you could contribute an integration test exercising the various Scala compilers, maybe I could do the rest. But I'm not sure this is even possible.

Also note that despite Gradle explicitly supporting annotation processing in Groovy code, this plugin doesn't support Groovy either.

Closing for now as wontfix; can reopen if I'm given sufficient information to possible do it.

**Comment by amnsinghl** [comment]
Any plans to add support for scala ?

**Comment by tbroyer** [comment]
> Any plans to add support for scala ?

No, because I have no plan for anything else than retiring this plugin. It has started losing usefulness since Gradle 4.3, and with 5.2 everything is baked into Gradle proper so the plugin has become completely useless. And this should apply to Scala as well.
