### ISSUE TITLE
eclipse.preferences.version vs eclipse.preference.version

### ISSUE THREAD

**Issue by sbraconnier** [tbroyer/gradle-apt-plugin#33]
Hi,

I think there is a little error in the org.eclipse.jdt.apt.core.prefs that is generated by the plugin (eclipse configuration).

It should be eclipse.preferences.version=1 instead of eclipse.preference.version=1 (missing s in preference).

I honestly do not know if there is an impact to this. I just had both properties in my org.eclipse.jdt.apt.core.prefs file.

**Comment by tbroyer** [comment]
Thanks. Fixed in f6aaa65e3b0e3aec5cec3e8abae93b296ae447ee

Also just released a v0.9 with the fix (but not only)
