### ISSUE TITLE
Update Intellij documentation per https://youtrack.jetbrains.com/issue/IDEA-156838

### ISSUE THREAD

**Issue by perlow** [tbroyer/gradle-apt-plugin#35]
https://youtrack.jetbrains.com/issue/IDEA-156838 may provide a better solution than unchecking "Create separate module per source set" as there are other undesirable side-effects of having a single module.

**Comment by tbroyer** [comment]
I'm having issues with this in 2016.2.4: in the Project Structure, IDEA insists in having `build/classes/main/generated` and `build/classes/test/generated` as source roots, and won't automatically configure `build/generated/source/apt/main` and `build/generated/source/apt/test` as source roots (so while `Rebuild project` succeeds, the editor display errors and squiggles where generated classes are used).

So this adds even more manual configuration, that doesn't scale well for big projects.

For that reason I'm a bit reticent to change the doc to recommend that configuration; though maybe I could update it to describe it: either use separate module per source set but then you'll have to add generated sources manually in the Project Structure screen, or use a single module and everything Just Works™ but you're losing the benefits of separate modules (I'd bet most projects do well with the single module approach). WDYT?

**Comment by perlow** [comment]
I've been having good luck with the following configuration:

![screen shot 2016-10-05 at 10 48 27 pm](https://cloud.githubusercontent.com/assets/439689/19141872/e4ace810-8b4d-11e6-888b-3516ed8838e9.png)

We've found the multiple modules better for two reasons:

1. The iteration cycle is faster for running the application as Intellij won't build the test sources unless you're trying to actually run a test. In our project, the tests seem to take much longer to build than the main code (perhaps b/c we're using groovy as well for some tests).

2. We had issues where Intellij keeps reordering the main and test libraries in the .iml file, which we have under source control. I guess it wasn't using a stable sort. This issue doesn't happen when it's built as separate modules. Now that I write this though, I realized we might not even need to check this into source control as its generated from the gradle file anyway.

**Comment by tmtron** [comment]
I've also used the parent-dir workaround and it works fine in IntelliJ 2016.3.4  

I keep "Module content root" active and set the directories like this:

- Production sources directory: `../main`
- Test sources directory: `../test`

![selection_039](https://cloud.githubusercontent.com/assets/20422904/23331291/2c39e2b6-fb63-11e6-876b-f815f9cc3899.png)

**Comment by tbroyer** [comment]
In IntelliJ IDEA 2016.3.4, the `apt` dependencies are apparently no longer added to the project when importing with “Create separate module per source set” checked (see #42). One more reason to leave the documentation the way it is.

I added a note about the 2016.3 new setting to delegate the build to Gradle, which should also solve the problem: https://www.jetbrains.com/idea/whatsnew/#v2016-3-gradle

**Comment by cal101** [comment]
Just a note regarding adding apt dependencies to the separate apt idea module: (2016.3.4)

```
    // added to idea apt module dependencies (classpath)
    aptCompile 'com.google.code.findbugs:jsr305:1.3.9'
```
