### ISSUE TITLE
Could you give me a howto on changing the destination directory

### ISSUE THREAD

**Issue by jw** [tbroyer/gradle-apt-plugin#36]
Thanks for this handy plugin.  We need to change the destination directory of the generated classes (to somewhere in the src folder), could you give us a hand?  Can you write a small gradle script?

**Comment by tbroyer** [comment]
For example, to have your `compileJava` task (the one that compiles the `main` source set) generate sources into `src/main/generated`, you'd use something like:

```gradle
sourceSets {
  main {
    output {
      generatedSourcesDir = 'src/main/generated'
    }
  }
}

// or the more compact equivalent:
// sourceSets.main.output.generatedSourcesDir = 'src/main/generated'
// or any intermediary variant
```

Or you could simply reconfigure the `compileJava` task (but you could theoretically have other tasks that default to the source set output `generatedSourcesDir`, so they wouldn't see the change; hence the above, configuring the source set output, is preferred):
```gradle
compileJava {
  generatedSourcesDestinationDir = 'src/main/generated'
}

// or the more compact equivalent:
// compileJava.generatedSourcesDestinationDir = 'src/main/generated'
```

To redirect all source sets' generated sources to `src/<source set name>/generated', you could write:

```gradle
sourceSets.all { sourceSet ->
  sourceSet.output.generatedSourcesDir = "src/${sourceSet.name}/generated"
}
```

See https://github.com/tbroyer/gradle-apt-plugin#configuration

**Comment by NachoSoto** [comment]
For anyone coming here trying to get this working, for some reason this didn't work for me (Gradle complained `main` was not found):
```groovy
sourceSets {
  main {
    output {
      generatedSourcesDir = 'src/main/generated'
    }
  }
}
```

But this did:
```groovy
sourceSets {
  main {
    output.generatedSourcesDir = 'src/main/generated'
  }
}
```
