### ISSUE TITLE
Option to disable or change IntelliJ source directories

### ISSUE THREAD

**Issue by kenzierocks** [tbroyer/gradle-apt-plugin#37]
When using this plugin by importing with `gradle idea`, Gradle and IntelliJ have a conflict regarding the generated files.

Because of https://github.com/tbroyer/gradle-apt-plugin/blob/master/src/main/groovy/net/ltgt/gradle/apt/AptPlugin.groovy#L224-L225, IntelliJ reads and compiles `build/generated/source/apt/main` (Gradle generated source). However, IntelliJ also runs the APs and writes the compiled `.class` files to `build/classes/main`. This creates duplication, and the only fix I can think of right now is removing those two lines so that the Gradle files do not conflict with the IntelliJ ones.

**Comment by tbroyer** [comment]
I can't reproduce. I don't generally use `gradle idea`, but just tried it on an existing project and didn't have any issue; I can run . Do you have a project I could try that on? Which version of Gradle and IntelliJ are you using? Do you have _Clear output directory on rebuild_ checked in _Settings_ → _Build, Execution, Deployment_ → _Compiler_? (though even with that unchecked I can't reproduce)

**Comment by kenzierocks** [comment]
I can't seem to reproduce this problem on the latest IntelliJ now. I'll re-open if it happens again, and get you a test project.
