### ISSUE TITLE
Make the plugin available on Maven Central/jcenter

### ISSUE THREAD

**Issue by mputters** [tbroyer/gradle-apt-plugin#40]
Hello,

Is there any chance you could make the plugin artifacts available on Maven Central or jcenter?

Thanks

**Comment by tbroyer** [comment]
See https://github.com/tbroyer/gradle-errorprone-plugin/issues/11

What's the actual problem with the Gradle Plugins portal?

**Comment by mputters** [comment]
The portal itself works fine, it's more a matter of being behind a corporate proxy with its own Nexus (that mirrors Maven Central but not the Gradle plugins portal).
I was just wondering if there was a specific reason not to have the plugin on those repositories, but I can certainly work around the (or my) issue.
