### ISSUE TITLE
Annotation processor in IntelliJ

### ISSUE THREAD

**Issue by tmtron** [tbroyer/gradle-apt-plugin#42]
I use [immutables](https://immutables.github.io/) in a small project: full source code is here [GitLab encoding](https://gitlab.com/tmtron-immutables/encoding)

when I setup my build.gradle as explained in the [readme file](https://github.com/tbroyer/gradle-apt-plugin/blob/master/README.md):

```gradle
dependencies {
  compileOnly "org.immutables:value:2.2.10:annotations"
  apt         "org.immutables:value:2.2.10"
}
```
the gradle command line build works.

When I apply the IntelliJ settings for annotation processors as explained in [my comment of issue#35](https://github.com/tbroyer/gradle-apt-plugin/issues/35#issuecomment-282482795), IntelliJ will still not run the annotation processors.  
I must also add `immutables:values` to the `compile` configuration, like this:
```gradle
dependencies {
  compileOnly "org.immutables:value:2.2.10:annotations"
  compile         "org.immutables:value:2.2.10"
  apt         "org.immutables:value:2.2.10"
}
```

Can someone please explain why this is needed?

**Comment by tbroyer** [comment]
I'll have a look, but FYI IntelliJ IDEA 2016.3 has an option to delegate build to Gradle; maybe you could try that?
https://www.jetbrains.com/idea/whatsnew/#v2016-3-gradle

(FWIW, I for one manually run a compilation through Gradle whenever I need to rerun annotation processors, I don't let IntelliJ IDEA do it for me)

**Comment by tbroyer** [comment]
OK, so `./gradlew idea` works as expected (adds `org.immutables:value:2.2.10` as a dependency), but the IntelliJ↔Gradle integration does not…

…**unless** you uncheck `Create separate module per source set` when importing the project.

I'd love to get better integration with IntelliJ IDEA but that would probably require changes to IntelliJ and/or Gradle. Ideally, annotation processors will eventually be first-class citizens in Gradle so this plugin will no longer be necessary and integration with IntelliJ could be much better. In the mean time, I don't have the bandwidth to even start reverse-engineering and debugging what IntelliJ does, and understand what could make it happy.

As stated in the README, IDE integration is provided as a best-effort, and IntelliJ has too many options and obscure behaviors (not to mention the recent changes to `gradle idea` in Gradle 3.4).

**Comment by tmtron** [comment]
thanks for the quick reply & the info about the "option to delegate build to Gradle". I didn't know about that, but it sounds great and I'll give it a try.
