### ISSUE TITLE
Intellij Idea do not generate classes

### ISSUE THREAD

**Issue by danielesegato** [tbroyer/gradle-apt-plugin#44]
Hi,

I've added this plugin to a test project I'm working on.

The annotation processor is invoked and I can see the generated classes if I execute gradle from the command line (`./gradlew assemble`) but they are not (actually they are deleted) if I rebuild the project in the IDE.

I'm talking about this version of the IDE:

```
IntelliJ IDEA 2017.1
Build #IC-171.3780.107, built on March 22, 2017
JRE: 1.8.0_112-release-736-b13 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-66-generic
```

root `build.gradle`:

```groovy
buildscript {
    repositories {
        jcenter()
        maven {
            // used for gradle-apt-plugin
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "net.ltgt.gradle:gradle-apt-plugin:0.9"
    }
}

plugins {
    id 'com.gradle.build-scan' version '1.6'
}

apply plugin: 'net.ltgt.apt'
apply plugin: 'idea'

buildScan {
    licenseAgreementUrl = 'https://gradle.com/terms-of-service'
    licenseAgree = 'yes'
    if (System.env.CI) {
        publishAlways()
    }
}

allprojects {
    apply plugin: 'idea'
    group 'my.group.id'
    version '1.0-SNAPSHOT'

    repositories {
        jcenter()
    }
}

apply from: rootProject.file('dependencies.gradle')
```

Then `settings.gradle`:

```groovy
include ':rx-scheduler-annotation'
include ':rx-scheduler-testing-annotation'
include ':rx-scheduler-testing-processor'
include ':rx-scheduler-sample'
```

The annotation processor is in the third module, the sample app use the annotation to generate classes.

rx-scheduler-testing-processor `build.gradle`:

```groovy
apply plugin: 'java'

sourceCompatibility = 1.8

dependencies {
    testCompile rootProject.ext.junit
    compile project (path: ':rx-scheduler-testing-annotation')

    compile rootProject.ext.guava
}
```

rx-scheduler-sample `build.gradle`:

```groovy
apply plugin: 'net.ltgt.apt'
apply plugin: 'java'
apply plugin: 'idea'

sourceCompatibility = 1.8

dependencies {
    testCompile rootProject.ext.junit
    apt project (path: ':rx-scheduler-testing-processor')
    compile project (path: ':rx-scheduler-testing-annotation')
}
```

I've imported the project in Intellij unchecking `Create separate module per source set` as instructed. I've enabled Annotation Processor with paths `build/generated/source/apt/main` and `build/generated/source/apt/test` and set `module content root`.

As you can see by the above gradle scripts all projects are applying the idea plugin. Sometimes I've even applied the plugin where it wasn't needed (out of option = try weird stuff)

The result when I hit the "rebuild" button on the IDE is that the generated folder is wiped. From gradle it is correctly generated, meaning my processor is working and is correctly configured.

What's going on here?

**Comment by danielesegato** [comment]
It is a test project with very basic stuff I wrote in like half day because I never wrote an annotation processor.

But it has company package, if I can send to you privately a zip / tgz file I'll happily share it with you.

**Comment by tbroyer** [comment]
My email address  can be found in the Git commits :wink: (hint: take any URL for a given commit and append `.patch` to it)

**Comment by tbroyer** [comment]
Closing as _inactive_ but feel free to followup here or by mail and I'll reopen if needed.

**Comment by danielesegato** [comment]
I'm sorry I though I sent you the package it must have slipped my mind.

I didn't work with apt since then so I completely forgot.

If you want to fix this issue I can prepare the package and send it to you tomorrow.

**Comment by tbroyer** [comment]
Could have ended up in my spam folder (but then must have been deleted by now). Ping me here when you send the mail and I'll have a look.

**Comment by danielesegato** [comment]
I've sent you an (ugly) project via email where you can reproduce it I think. Ty

**Comment by tbroyer** [comment]
It looks like this is due to the processor being a module in the same project. If I add:
```gradle
apt 'com.google.auto.value:auto-value:1.4.1'
compileOnly 'com.google.auto.value:auto-value:1.4.1'
```
in the same module that uses the annotation processor and a simple class:
```java
abstract class SampleValueObject {
  abstract String foo();
}
```
then an `AutoValue_SampleValueObject.java` is properly generated in `build/generated/source/apt/main`.

To be confirmed but this is highly likely to be independent from using this plugin, or even Gradle.

**Comment by tbroyer** [comment]
You can choose the other option to _Delegate IDE build/run actions to gradle_ (in _Build, Execution, Deployment →Build Tools → Gradle → Runner_ starting with IDEA 2016.3), and you can then even _Create separate module per source set_, and don't have to configure annotation processing in the IDE at all.

**Comment by danielesegato** [comment]
I'm sorry but isn't that the standard use you make of an annotation processor?

you are supposed to use it as a library developed somewhere else.

Are you saying this would work as expected if I instead published the module in an artifact repository and declared it as dependency through that?

If I understand the issue correctly you are also saying this is a bug with the IDE?

**Comment by tbroyer** [comment]
> Are you saying this would work as expected if I instead published the module in an artifact repository and declared it as dependency through that?
> 
> If I understand the issue correctly you are also saying this is a bug with the IDE?

Yes, that's what I'm saying.

It does work if you specify (in IDEA annotation processing settings) the FQCN of the processor though, so the problem actually seems to be in discovery of the processors (IDEA finds the AutoValue processor in the external JAR, but not the processor from the other module in the project)

…to be confirmed (e.g. by creating an IDEA project from scratch, not involving Gradle); but the processor module is correctly added as a dependency of the module that uses it (so the gradle-apt-plugin is working as expected).

**Comment by danielesegato** [comment]
Thank you, tomorrow I'm gonna open a bug to Intellij Idea pointing to this issue. And linking the issue here.
I'd appreciate if you could add any useful technical detail I could miss with my reporting.

**Comment by danielesegato** [comment]
Looks like they already have a bug about it, almost 2 years old:
https://youtrack.jetbrains.com/issue/IDEA-143480

I added a comment

**Comment by dthommes** [comment]
**Workaround:**
Add the annotation processor as `compileOnly` dependency in your gradle file. You may keep your `annotationProcessor` dependency additionally. IntelliJ only then recognizes it as being part of the classpath. As it looks in the module's classpath for annotation processors, it will from then on start generating.

**Comment by tbroyer** [comment]
@dthommes Just be careful about dependency conflict resolution (e.g. you use Guava 20 for some reason, but will actually compile against 26 because an annotation processor now brings it in the `compileOnly` configuration; but at runtime you'll still have 20, so your code might have been compiled against new 26.0 APIs and will fail at runtime)
