### ISSUE TITLE
gradle do not generate general java sources from src/main folder

### ISSUE THREAD

**Issue by IuriiSergiichuk** [tbroyer/gradle-apt-plugin#46]
Hello.
I'm trying to use [dagger2](https://github.com/google/dagger) with your plugin in multi-module gradle project, but I cannot configure plugin for gradle usage properly, maybe you can help me and point where the problem could be?

I've checked in test dagger2 module into the example project I'm currently trying to setup, so you can simply clone the repository and try to run `gradlew clean build` - as the result - there won't be any sources in the `build/classes/main` folder under the `dagger` module.

Here is the repository link: [https://github.com/xSAVIKx/appengine-gradle-plugin-test](https://github.com/xSAVIKx/appengine-gradle-plugin-test)

In order to show, that without your plugin sources are compiled properly, please change `dagger/build.gradle` file with following content:
```groovy
//apply plugin: "net.ltgt.apt"

dependencies {
    compile libraries['dagger']
    compile libraries['javax.inject']
//    apt libraries['dagger-compiler']
    testCompile libraries['junit']
}
```

Also, I'd like to say, that I'll, for example, run any test in the module, that is using Dagger2 or will run any `main` method - IDEA will compile and generate all needed classes, but Dagger2 generated classes won't be pointed as IDEA sources. (I've check annotation processing in IDEA manually)

I'm using IDEA 2017.1 and:
```
$ gradlew --version

 ------------------------------------------------------------
Gradle 3.4.1
------------------------------------------------------------

Build time:   2017-03-03 19:45:41 UTC
Revision:     9eb76efdd3d034dc506c719dac2955efb5ff9a93

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.7.0_79 (Oracle Corporation 24.79-b02)
OS:           Windows 8.1 6.3 amd64
```

**Comment by tbroyer** [comment]
The reason is because Dagger 2.10 requires Java 8, and for some reason `javac` from a JDK 7 won't complain when it can't load an incompatible class for an annotation processor.

You need to update to Java 8 (this is a good idea anyway), or downgrade Dagger to a version that works with Java 7.

**Comment by IuriiSergiichuk** [comment]
@tbroyer Thanks for the answer.

Yeap, really, when I tried to point gradle to use java8 instead of java7 everything was compiled properly.
