### ISSUE TITLE
Can we use processor with project ? Error:Gradle: Attempt to recreate a file for type

### ISSUE THREAD

**Issue by kowlown** [tbroyer/gradle-apt-plugin#47]
I try to use an annotation processor

The structure of my project is this one :
- androidApplication
- coreLibrary
- procossorLibrary
	- annotations
	- processor

The androidApplication is just an empty shell since the majority of the code is in coreLibrary.

In the gradle file of core library I added :

```
apply plugin: 'java'
apply plugin: 'idea'
apply plugin: "net.ltgt.apt"

sourceCompatibility = 1.7
[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'

dependencies {
    //    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile "com.badlogicgames.gdx:gdx:$gdxVersion"
    compile "com.github.czyzby:gdx-kiwi:1.7.$gdxVersion"
    compile 'com.badlogicgames.gdx:gdx-ai:1.8.0'
    compile 'com.google.code.gson:gson:2.7'
    compile 'com.google.guava:guava:19.0'
    compile "com.kotcrab.vis:vis-ui:$visuiVersion"
    compile "com.badlogicgames.gdx:gdx-freetype:$gdxVersion"

    compile project(':lualib:jse')
    compile project(':procossorLibrary:annotations')
    apt project(':procossorLibrary:processor')
}

```

But when I make the project I have the error : 

Error:Gradle: Attempt to recreate a file for type <The full classname of the Java file I when to generate>

**Comment by tbroyer** [comment]
> Can we use processor with project?

Yes.

I just added a test to make sure it works (I thought I already had one): 0b8ff4d3dc40004667a5c74e3746a363d4ae9f2d

Try running Gradle with `--stacktrace`. I believe you have a bug in your annotation processor.

**Comment by kowlown** [comment]
I have a simple annotation processor :

`package com.mystnihon.registrations.actions;

import com.google.auto.service.AutoService;
import com.mystnihon.registrations.RegisterAction;

import java.io.IOException;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.Filer;
import javax.annotation.processing.Messager;
import javax.annotation.processing.ProcessingEnvironment;
import javax.annotation.processing.Processor;
import javax.annotation.processing.RoundEnvironment;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.TypeElement;
import javax.lang.model.util.Elements;
import javax.lang.model.util.Types;
import javax.tools.Diagnostic;

/**
 * Default template
 */

@AutoService(Processor.class)
public class ActionRegistrationProcessor extends AbstractProcessor {

    private Types typeUtils;
    private Elements elementUtils;
    private Filer filer;
    private Messager messager;

    public ActionRegistrationProcessor() {
    }

    @Override
    public synchronized void init(ProcessingEnvironment processingEnv) {
        super.init(processingEnv);
        typeUtils = processingEnv.getTypeUtils();
        elementUtils = processingEnv.getElementUtils();
        filer = processingEnv.getFiler();
        messager = processingEnv.getMessager();
    }

    @Override
    public boolean process(Set<? extends TypeElement> set, RoundEnvironment roundEnvironment) {
        return proccessUtil(roundEnvironment);
    }

    private boolean proccessUtil(RoundEnvironment roundEnvironment) {
        List<Element> annotatedElements = new ArrayList<>();

        ActionAnnotatedClass actionAnnotatedClass = new ActionAnnotatedClass(elementUtils, typeUtils, annotatedElements);
        try {
            actionAnnotatedClass.generateCode(filer);
        } catch (IOException e) {
            messager.printMessage(Diagnostic.Kind.ERROR, e.getMessage());
        }
        return true;
    }

    @Override
    public Set<String> getSupportedAnnotationTypes() {
        Set<String> annotataions = new LinkedHashSet<>();
        annotataions.add(RegisterAction.class.getCanonicalName());
        return annotataions;
    }

    @Override
    public SourceVersion getSupportedSourceVersion() {
        return SourceVersion.latestSupported();
    }
}`



And `package com.mystnihon.registrations.actions;

import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.TypeSpec;

import java.io.IOException;
import java.util.List;
import java.util.Random;

import javax.annotation.processing.Filer;
import javax.lang.model.element.Element;
import javax.lang.model.element.Modifier;
import javax.lang.model.util.Elements;
import javax.lang.model.util.Types;

/**
 * Default template
 * Created by llirvat on 05/04/2017.
 */

public class ActionAnnotatedClass {

    private final Elements mElementUtils;
    private final Types mTypeUtils;
    private final List<Element> mAnnotatedElement;


    public ActionAnnotatedClass(Elements elementUtils, Types typeUtils, List<Element> annotatedElement) {
        mElementUtils = elementUtils;
        mTypeUtils = typeUtils;
        mAnnotatedElement = annotatedElement;
    }

    public void generateCode(Filer filer) throws IOException {
        final String className = "Registration" + new Random().nextInt(10000);

        TypeSpec.Builder builder = TypeSpec.classBuilder(className).addModifiers(Modifier.PUBLIC);

        TypeSpec typeSpecRegistration = builder.build();

        JavaFile javaFile = JavaFile.builder("fr.telecom.idiom.langage", typeSpecRegistration).build();

        javaFile.writeTo(filer);
    }

}
`
**It generates multiple Registration file like it was called multiple time instead of once.**

I use this annotation processor declaration and I didn't had this problem when using maven. Sadly on this one I have to use gradle..
