### ISSUE TITLE
Annotation processing doesn't work for groovy tests

### ISSUE THREAD

**Issue by erikhofer** [tbroyer/gradle-apt-plugin#49]
I placed an annotation on a groovy class in `src/test/groovy`. I added a `testApt` dependency. The annotation doesn't get processed. Java does work.

```
compileGroovy {
  groovyOptions.javaAnnotationProcessing = true
}
```
This setting doesn't seem to affect the `compileTestGroovy` task. Is there an equivilent that is missing in the documentation?

**Comment by tbroyer** [comment]
This snippet indeed only configures the `compileGroovy` task. To configure the `compileTestGroovy`:

```grooovy
compileTestGroovy {
  groovyOptions.javaAnnotationProcessing = true
}
```

Or to configure all `GroovyCompile` tasks in one go:
```groovy
tasks.withType(GroovyCompile) {
  groovyOptions.javaAnnotationProcessing = true
}
```

I'm not going to add this to the doc though, it's not a doc about using Gradle itself.
