### ISSUE TITLE
add processor options to eclipse settings

### ISSUE THREAD

**Issue by OverDrone** [tbroyer/gradle-apt-plugin#50]
Please add something like code below to eclipseJdtApt task (and maybe similar changes to idea task):
tasks.findByName('eclipseJdtApt') << {
  compileJava.aptOptions.processorArgs.each { k, v ->
    aptPrefs.text += "org.eclipse.jdt.apt.processorOptions/${k}=${v}\n";
  }
}

**Comment by tbroyer** [comment]
Fixed by 1807f3d87bc761cb63d46efeed10aee177d42629 and later commits. Eclipse processor options default to `compileJava.aptOptions.processorArgs` (i.e. options for the `main` source set, that will also apply to test sources in Eclipse).

**Comment by tbroyer** [comment]
Just published v0.11 with those changes; please test and report any regression, or any issue with the new behavior.

**Comment by thekalinga** [comment]
@tbroyer Is there a similar option for IntelliJ aswell for settingup processor options automatically?

**Comment by thekalinga** [comment]
I tried using this, but the processor options are not added automatically
