### ISSUE TITLE
Issue running the JPAAnnotationProcessor from QueryDSL

### ISSUE THREAD

**Issue by balteo** [tbroyer/gradle-apt-plugin#51]
I am trying to get QueryDSL apt to work with the gradle apt plugin.

I have opened a thread on SO here: https://stackoverflow.com/questions/44876016

Can you confirm whether or not the gradle apt plugin is able to configure QueryDSL?

**Comment by tbroyer** [comment]
Yes, the plugin is mostly some DSL to help configure compilation tasks, so it "works" with any annotation processor.

The fact that you have

```
Note: Running JPAAnnotationProcessor
```

in your build log means that it correctly configured the task. Now, that specific processor has additional requirements.
