### ISSUE TITLE
Add support for use of generated objects in Kotlin

### ISSUE THREAD

**Issue by utwyko** [tbroyer/gradle-apt-plugin#53]
We're currently moving a project with a lot of [Immutables](https://github.com/immutables/immutables/) objects to Kotlin. Since we prefer incremental refactoring, it would be great of we could use those objects, generated based on annotations in Java files, in our Kotlin code. 

Something like the current Groovy support would be perfect. There is no need for actual kotlin annotation processing, since that is covered by [kapt](https://kotlinlang.org/docs/reference/kapt.html)

**Comment by tbroyer** [comment]
FWIW, the so-called _Groovy support_ is “only” about configuring the `GroovyCompile` tasks in addition to the `JavaCompile` tasks: https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.GroovyCompile.html#org.gradle.api.tasks.compile.GroovyCompile:options

Could you share a small repro case / project to help me understand your use-case?

**Comment by utwyko** [comment]
Hi @tbroyer, thanks for the quick response. I think the configuration of the `GroovyCompile` (or in this case the `KotlinCompile` task _should_ be enough, but I'm not that familiar with the actual gradle compilation process.

I've created an example project [here](https://github.com/utwyko/gradle-apt-with-kotlin).

**Comment by tbroyer** [comment]
Is Kotlin code compiled before or after Java code?

**Comment by utwyko** [comment]
@tbroyer Kotlin code is compiled during the Java compilation, because due to the interoperable nature you can have Java Class A depend on Kotlin Class A depend on Java Class B constructions. 

But I've actually already found a solution: switch to kapt completely! I missed this line in the documentation:
> If your project contains Java classes, kapt will also take care of them.

Removing gradle-apt and replacing it with kapt makes my example project compile. 

Thanks for your help!
