### ISSUE TITLE
Add option to configure org.eclipse.jdt.apt.genSrcDir

### ISSUE THREAD

**Issue by dpolivaev** [tbroyer/gradle-apt-plugin#54]
Currently fix value '.apt_generated' is used. This directory is filtered out by default eclipse file filter in package explorer. It would be nice this directory could be configured.

**Comment by tbroyer** [comment]
FWIW, currently working on it as part of #50 

Should be:
```gradle
eclipseJdtApt {
  genSrcDir = file('whatever')
}
```

**Comment by tbroyer** [comment]
Fixed by 1807f3d87bc761cb63d46efeed10aee177d42629, later modified to eventually make things configurable as:

```gradle
eclipse {
  jdt {
    apt {
      genSrcDir = file('whatever')
    }
  }
}
```

**Comment by tbroyer** [comment]
Just published v0.11 with those changes; please test and report any regression, or any issue with the new behavior.

**Comment by dpolivaev** [comment]
I have checked it.

Just writing 
~~~
plugins {
	id "net.ltgt.apt" version "0.11"
  }
~~~
was not enough to get it work. I needed to add lines 
~~~
apply plugin: "net.ltgt.apt-eclipse"
apply plugin: 'java-library' 
~~~

I have created a test project https://github.com/dpolivaev/jackson-immutables-gradle-test you can use for your tests. I shall delete this repository after you either fix the issue or change the documentation.

**Comment by dpolivaev** [comment]
Many thanks for implementing the feature.

**Comment by dpolivaev** [comment]
Added https://github.com/tbroyer/gradle-apt-plugin/issues/57
