### ISSUE TITLE
Plugins v0.11 are not completely applied by default

### ISSUE THREAD

**Issue by dpolivaev** [tbroyer/gradle-apt-plugin#57]
Just writing 
~~~
plugins {
	id "net.ltgt.apt" version "0.11"
  }
~~~
was not enough to get it work. I needed to add lines 
~~~
apply plugin: "net.ltgt.apt-eclipse"
apply plugin: 'java-library' 
~~~

I have created a test project https://github.com/dpolivaev/jackson-immutables-gradle-test you can use for your tests. I shall delete this repository after you either fix the issue or change the documentation.

**Comment by tbroyer** [comment]
I see nothing wrong/unexpected in this repository.

`java-library` (or `java`) plugin is needed to make it a Java project, with the corresponding source sets, configurations (`compile`, `compileOnly`, and `testCompile`), and tasks.

`eclipse` plugin is needed to get the `eclipse` DSL, and the  `eclipse.jdt` DSL is avialable through the combination of both `eclipse` and `java` plugins.

`net.ltgt.apt-eclipse` plugin will apply the `eclipse` plugin (`java-library` will apply the `java` plugin) and create the `eclipse.jdt.apt` DSL.

What were you expecting? (both/either as behavior and/or documentation)

**Comment by jimmywan** [comment]
@tbroyer Unless I'm missing something, what you've stated is not reflected in the instructions here:
https://plugins.gradle.org/plugin/net.ltgt.apt

**Comment by tbroyer** [comment]
That's right. See the README here (linked from the plugin portal), and https://plugins.gradle.org/plugin/net.ltgt.apt-idea and https://plugins.gradle.org/plugin/net.ltgt.apt-eclipse

**Comment by jimmywan** [comment]
Ohh, I see. Somewhat easy to gloss over the fact that net.ltgt.apt-idea and net.ltgt.apt-eclipse are separate plugins. Thanks for the clarification.
