### ISSUE TITLE
Support for NetBeans

### ISSUE THREAD

**Issue by gtheimer** [tbroyer/gradle-apt-plugin#59]
What is the chance of a gradle-apt-plugin for NetBeans? I'd want to use Dagger 2 with NetBeans. Unfortunately, NetBeans 8.2 does not see the generated Java source code and complains about unresolved symbols. 

Any work-around suggestions besides switching the IDE?

**Comment by tbroyer** [comment]
Assuming your using this plugin, it says it configures itself from the IDEA configuration: https://github.com/kelemen/netbeans-gradle-project/#the-classpaths-are-wrong-within-netbeans

Have you tried that?

**Comment by gtheimer** [comment]
I am looking into this. Thank you!
