### ISSUE TITLE
IntelliJ 15 does not run the annotation processor as part of its built in make process.

### ISSUE THREAD

**Issue by yogurtearl** [tbroyer/gradle-apt-plugin#6]
On IntelliJ 15 Preview with gradle 2.7:

Plugins:
```
plugins {
  id 'java'
  id 'application'
  id 'idea'
  id 'net.ltgt.apt' version "0.4"
}
```

AutoValue:
```
  compileOnly "com.google.auto.value:auto-value:$depVersions.autovalue"
  apt "com.google.auto.value:auto-value:$depVersions.autovalue"
```

If I build only in IntelliJ make ( not in gradle ), the generated AutoValue classes won't get created.

This IntelliJ config fixes the problem, but seem like the gradle plugins should cause this to happen automatically.

![image](https://cloud.githubusercontent.com/assets/1195562/10237453/6fe0135a-6866-11e5-806b-b53800b83d8c.png)

Maybe this needs to be an bug on IntelliJ's tracker...

**Comment by tbroyer** [comment]
Yup. Read the [README](https://github.com/tbroyer/gradle-apt-plugin/blob/fa4c0565c11ce6f07f57a2a1e86842c8dac25a18/README.md#usage-with-ides) more closely about setting up IDEs ;-)

It can hardly be imputed to either this plugin or JetBrains. It's a Gradle issue (request for enhancement) for not treating annotation processing as a first-class citizen and not exposing it in the tooling APIs that IntelliJ and Eclipse (can) use. See https://groups.google.com/d/topic/gradle-dev/w3aQgjY7mQk
