### ISSUE TITLE
  ClassNotFoundException in AnnotationProcessor's process method  when  use Class.forName(<my annotation class>)

### ISSUE THREAD

**Issue by lugreen** [tbroyer/gradle-apt-plugin#63]
Hi,
I use  a  [AnnotationProcessor ](https://github.com/ralscha/extclassgenerator)   generate some javacript model class within Intellij IDEA .
When i execute compileGroovy task in my gradle build,my annotationProcessor can be execute,and can find the annotaioned class,but when get the Class object , there throw ClassNotFoundException.see pickure below:
![classnotfoundexception](https://user-images.githubusercontent.com/1725996/31603877-236588f0-b294-11e7-8eab-c8f1869572c5.png)
It seems like the classloader can't find  my Model class ,how shoud i handle this problem?
Enviroment: 
Java8
Gradle4.1
gradle-apt-plugin:0.12
IDEA: 2017.2.5
Thanks!

**Comment by tbroyer** [comment]
Apparently, this annotation processor expects your annotated class to be in the same "classpath" as the annotation processor (see https://github.com/ralscha/extclassgenerator/blob/cf186f52e97d9599e25381a8ad79e26bd52fd936/src/main/java/ch/rasc/extclassgenerator/ModelAnnotationProcessor.java#L137-L138), which is not the case when you (purposefully) segregate them into `-classpath` and `-processorpath`.

Please file a bug on https://github.com/ralscha/extclassgenerator/ that the annotation processor does not work in your context.

**Comment by lugreen** [comment]
Hi,
Thanks very much!
I will try it.
