### ISSUE TITLE
The "Generated source directory" in Eclipse is not set by gradle-apt-plugin.

### ISSUE THREAD

**Issue by flasheater** [tbroyer/gradle-apt-plugin#7]
## Setup
* Java project in Eclipse Mars 4.5 with [Buildship](https://projects.eclipse.org/projects/tools.buildship) 1.0.5.
* Fedora 22
* Gradle 2.7

## What was done
1. Refresh gradle model inside eclipse using buildship. `right-click on project in eclipse`->`Gradle`->`Refresh Gradle Project`.
2. Run `$ ./gradlew eclipse`

## What happened
1. Nothing. Eclipse project is not configured to use annotation processing. While inconvenient, I suspect this has rather to do with Buildship itself.
2. Annotation Processing is enabled and the correct Factory Path is set. However the `Generated source directory` still points to the default `.apt_generated`.

## What was expected
1. I expected buildship to call `gradle eclipse` somehow internally. But that doesn't seem to be the case.
2. The "Generated source directory" should point to `build/generated/source/apt/main`.

## What was tried
Manually correcting the path in the eclipse settings seems to be the only solution. However, subsequent calls to `gradle eclipse` overwrite it again with `.apt_generated`.

It remains unclear to me what can be done about `build/generated/source/apt/test` as Eclipse does not seem to support such a configuration.

Here is the [`build.gradle`](http://hastebin.com/kumelumura.hs) file that was used.

**Comment by flasheater** [comment]
Also found 
`    aptSettings.getProperty('org.eclipse.jdt.apt.genSrcDir') == '.apt_generated' `
on line 110 in `gradle-apt-plugin/src/test/groovy/net/ltgt/gradle/apt/EclipseIntegrationSpec.groovy`.
Shouldn't it be 
`    aptSettings.getProperty('org.eclipse.jdt.apt.genSrcDir') == 'build/generated/source/apt/main' `?

What am I misunderstanding?

**Comment by tbroyer** [comment]
`.apt_generated` is used for the same reason that Buildship (and `gradle eclipse`) also uses `bin` as output folder: Eclipse only has one buildpath/classpath per project, so to avoid mixing main and test outputs with the Gradle build, Eclipse is configured to use its own output folders, distinct from the ones the Gradle build uses.

I'll update the README wrt Buildship though as it requires manual configuration, just like IntelliJ IDEA.

**Comment by flasheater** [comment]
I see. Thank you for clarifying.

Thomas Broyer <notifications@github.com> schrieb am So., 18. Okt. 2015,
21:20:
