### ISSUE TITLE
Custom sourceset support for IntelliJ

### ISSUE THREAD

**Issue by rolfw** [tbroyer/gradle-apt-plugin#70]
I've added a sourceSet `model` to an existing java project. I'm delegating the build to Gradle as recommended and everything works fine for standard sourceSets, also after adding the custom sourceSet. It doesn't apply the same configuration for the model sourceSets though;

The problem is that the generated sources directory is not added as a content root. Since the Gradle build was successful, it works fine when I add the directory manually (`File -> Project Structure -> Modules -> model -> Add Content Root -> build/generated/source/apt/model) and mark it as generated. But when I refresh the Gradle project my changes are lost.

These are relevant parts of my build script:

```
plugins {
	id "java"
	id "idea"
	id "application"
	id "net.ltgt.apt" version "0.13"
	id "net.ltgt.apt-idea" version "0.13"
}

sourceSets {
	model {

	}

	main {
		compileClasspath += model.compileClasspath + model.output
	}

	test {
		compileClasspath += main.compileClasspath + main.output
		compileClasspath += modelTestSupport.compileClasspath + modelTestSupport.output
	}
}

dependencies {
	apt "com.google.dagger:dagger-compiler:$daggerVersion"
	apt "org.immutables:value:$immutablesVersion"
	modelApt "org.immutables:value:$immutablesVersion"

	compileOnly "com.google.dagger:dagger:$daggerVersion"
	compileOnly "org.immutables:builder:$immutablesVersion"
	compileOnly "org.immutables:value:$immutablesVersion"
	modelCompileOnly "org.immutables:builder:$immutablesVersion"
	modelCompileOnly "org.immutables:value:$immutablesVersion"
} 
```

When I add `sourceSets.model.java.srcDir new File(buildDir, 'generated/source/apt/model')` it works, but I have to clean between each build due to this issue: ["IllegalStateException: endPosTable already set" when adding apt output to sourcesets](https://github.com/tbroyer/gradle-apt-plugin/issues/23)

Annotation processing works smooth for additional source sets for regular Gradle builds, just like for the standard source sets (thanks for your plugin :) It just doesn't work for IntelliJ Idea.

Looking at [AptIdeaPlugin.java](https://github.com/tbroyer/gradle-apt-plugin/blob/master/src/main/java/net/ltgt/gradle/apt/AptIdeaPlugin.java), it seems that additional source sets are currently not supported; If so, it would be great if this could be added. What can I do now to make it work without issues?

**Comment by tbroyer** [comment]
Does it work if you add:

```gradle
idea.module.generatedSourceDirs += sourceSets.model.output.generatedSourcesDir
```

to your build script? (maybe also add the same line but with `idea.model.sourceDirs`)

**Comment by rolfw** [comment]
Thanks for the suggestion. That would be a fine solution and I can see the sourceset added. The only remaining issue with this approach is that it adds it to the main sourceset, not to the model sourceset.

I've tried various approaches to access a specific module using the DSL. I could probably do it by manipulating the XML, but I expect that comes with much debugging and is less readable and maintainable than using the DSL. And I'd say it should be possible since the properties are there.

I asked a question on SO too: [Gradle idea plugin: add sourceDirs to specific module](https://stackoverflow.com/questions/47339005/gradle-idea-plugin-add-sourcedirs-to-specific-module)

There is a `modules` property on the `IdeaProject` type, but there is only one module there. Do you know if this approach should work, and how to make it work?

**Comment by tbroyer** [comment]
The thing is, the `idea` plugin and its DSL are mainly for using the `idea` task. When importing the project using IntelliJ IDEA's integration, it reads the values (if present), but will otherwise look at the project using Gradle APIs (you can see the logic in https://github.com/JetBrains/intellij-community/tree/master/plugins/gradle/ ), which allows it to see all the source sets (vs. only `main` and `test`).
With the recent way of creating a module per source set, the IDEA model no longer follows the `idea`-plugin model at all, but they try to reconcile them anyway.

I'll dig into the IDEA source code to try to understand if it's possible to do it, but I'm confident that they'll eventually take into account the new-in-Gradle-4.3 [`options.annotationProcessorGeneratedSourcesDirectory`](https://docs.gradle.org/4.3/release-notes.html#specify-output-directory-for-source-files-generated-by-annotation-processor) when importing a project.

With a bit of luck, this very plugin won't be needed eventually, except possibly to automatically create the `apt` configurations for each source set (Gradle developers think it's a bit overkill and would slow all builds and that's why they don't plan doing it by default in Gradle itself), but when there'll be only that left, I'll probably retire the plugin anyway as it could be done in only a handful of lines in your build script.

**Comment by rolfw** [comment]
Thanks for the background info. Indeed, I think it should be part of the java plugin since it's so common. I don't know the internals of Gradle, but surely they could avoid slowing the build by not loading any apt-related code when it's not requested in the build script?

Anyway, I did find a workaround by adding the sources to the srcDir property but I have to clean between each build due to this issue: ["IllegalStateException: endPosTable already set" when adding apt output to sourcesets](https://github.com/tbroyer/gradle-apt-plugin/issues/23); Do you happen to know a workaround for that for the time being?

**Comment by rolfw** [comment]
For anyone interested, I found a good workaround for this issue (which is actually [an issue in IntelliJ's Gradle Plugin](https://intellij-support.jetbrains.com/hc/en-us/requests/1150096)):

```
/*
* Reason for workaround:
*  IntelliJ's Gradle Plugin currently doesn't add generated sources to modules for any sourceSet
*  other than main and test.
*
*  The suggested workaround is to add generated sources to the srcDirs
*  property of the custom source sets, but this causes java compilation to fail with
*  "java.lang.IllegalStateException: endPosTable already set", probably because the generated sources
*  now appear twice on the classpath.
*  
*  Another problem is that code formatters such as spotless and
*  hierynomus/gradle-license-plugin format any source defined in each sourceSet, preventing incremental
*  builds from working (because formatters change the output of the compile tasks).
*
*  See https://intellij-support.jetbrains.com/hc/en-us/requests/1150096
*
* How this solution works:
*  IntelliJ appears to get the information it needs for configuring modules after Gradle's configuration phase, while the
*  problems in the build happen during the execution phase. So we add the paths for generated sources to each source set in the configuration
*  phase, and remove them again just before the execution phase.
*
* Caveat:
*  Generated sources will be added, but will not be seen as generated by Intellij (i.e.
*  they are seen as regular sources).
*/

project.afterEvaluate {

    sourceSets.each { SourceSet sourceSet ->

        // ====  Skip the standard sourcesets, which already work without problems  =====
        if (sourceSet.name != 'main' && sourceSet.name != 'test') {

            JavaCompile javaCompileTask = tasks[sourceSet.getCompileTaskName('java')]

            // ====  Add generated sources to the sourceset's source directories  =====
            sourceSet.java.srcDirs += javaCompileTask.generatedSourcesDestinationDir
        }
    }
}

gradle.taskGraph.whenReady {

    sourceSets.each { SourceSet sourceSet ->

        // ====  Skip the standard sourcesets, which haven't been changed in project.afterEvaluate  =====
        if (sourceSet.name != 'main' && sourceSet.name != 'test') {

            JavaCompile javaCompileTask = tasks[sourceSet.getCompileTaskName('java')]

            // ====  Remove generated sources that were previously added  =====
            sourceSet.java.srcDirs -= javaCompileTask.generatedSourcesDestinationDir
        }
    }
}
```
