### ISSUE TITLE
Tests failing with lombok and apt plugin

### ISSUE THREAD

**Issue by dcalap** [tbroyer/gradle-apt-plugin#73]
Hi, I have a project with mapstructs and lombok based on the mapstruct-examples/mapstruct-lombok/ but with latests versions, and tests part is not working.

Even adding lombok dependency in testCompile the lombok annotations used in tests are failing when executing gradle test task.

The problem starts when I add the apt plugin:

    plugins {
	    id 'net.ltgt.apt' version '0.13'  
    }

and the apt at depencencies:

    dependencies {
        ...
        apt "org.mapstruct:mapstruct-processor:${mapstructVersion}", "org.projectlombok:lombok"
        ...
    }

At this point the lombok annotations stop working and fails in compilaJavaTest gradle task.

Not adding apt plugin makes lombok work properly but then I can't use mapstructs 

Any idea?

Thanks.

**Comment by tbroyer** [comment]
If things fail in `compileJavaTest`, then maybe you need to use `aptTest` too (assuming you're now using mapstructs and/or lombok in the tests; something the example project doesn't do); the `apt` configuration only applies to the `compileJava` (and `compileGroovy`) task, there's no "inheritance" from main to test.

Also, you'll probably want to move the lombok dependency from `compile` to `compileOnly` (and then add it to `testCompileOnly`, as `testCompileOnly` doesn't extend from `compileOnly`; contrary to `testCompile` vs. `compile`); see https://projectlombok.org/setup/gradle & https://docs.gradle.org/4.3.1/userguide/java_plugin.html#sec:java_plugin_and_dependency_management

**Comment by dcalap** [comment]
Sorry! I haven't seen the testApt (there is a typo in the order of the words for the command you wrote in the answer :)) 

Now is working! Thanks a lot!

**Comment by tbroyer** [comment]
Ah yes, I regularly try to use `compileTest` instead of `testCompile` (for whatever reason, using `implementation` vs. `testImplementation` apparently seems to help).
Glad you found the correct syntax and it fixed your problem. You may want to (just a suggestion) file an issue on mapstruct-examples so they use mapstruct and/or lombok in tests too in their example, for the next one who tries it and doesn't understand why it fails and how to fix it.

**Comment by dcalap** [comment]
Sure, I opened an issue in order they include tests and give the advice of testApt and the link to this issue :)

Regards
