### ISSUE TITLE
project dependencies not build during eclipseFactorypath tasks

### ISSUE THREAD

**Issue by lennartfricke** [tbroyer/gradle-apt-plugin#77]
Hello,
I expected project dependencies to be build during the eclipseFactorypath task.
This is unfortunately not the case, as the plusConfigurations are not used as input for the eclipseFactorypath task.
Maybe the should be declared as TaskInputs. Behaviour observed with Gradle 4.5, apt 0.13.

**Comment by tbroyer** [comment]
Thanks for the report. Fixed by a958f7d in the just-released 0.14.
