### ISSUE TITLE
Should be possible to include only specific package to apt processing.

### ISSUE THREAD

**Issue by antiso** [tbroyer/gradle-apt-plugin#8]
It's possible to process only specific package but it involves main source set configuration thus java compiler is only applied to specified package too.

**Comment by tbroyer** [comment]
JavaC doesn't support such filtering, so there would have to be several JavaC passes. That'd mean the plugin would have to create `JavaCompile` tasks, not just configure existing ones.

Clearly this isn't worth the added complexity; plus, I have no idea how you'd configure that without being tied to the Java plugin's convention (losing flexibility) or applying the package filter to all tasks and source sets.

I suppose though you could write a plugin that would create and configure the `JavaCompile` tasks and the apt plugin.

**Comment by tbroyer** [comment]
BTW, instead of segmenting your source sets, maybe try using JavaC with `-proc:only` (along with a sourcepath containing all your sources) and `-proc:none`.

**Comment by antiso** [comment]
Ok. I'm not really familiar with gradle so thank you for clarification.

On Tue, Oct 20, 2015 at 9:25 AM, Thomas Broyer <notifications@github.com>
wrote:

> BTW, instead of segmenting your source sets, maybe try using JavaC with
> -proc:only (along with a sourcepath containing all your sources) and
> -proc:none.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tbroyer/gradle-apt-plugin/issues/8#issuecomment-149446953>
> .
>



-- 
Regards,
Vladimir
