### ISSUE TITLE
What's the purpose of this plugin?

### ISSUE THREAD

**Issue by rybak** [tbroyer/gradle-apt-plugin#80]
I was under the impression that just adding required annotation processor to the `compileOnly` configuration (or just into classpath for an Ant build) is enough for javac to find it.  Could you please clarify what does this plugin do other than pass annotation processor into classpath for the javac call?

**Comment by wemu** [comment]
Thanks for the reply! 

So a use case would be for example JPA Annotations to generate some helping classes? That then can be used elsewehere in the code? (the projects I see use some Hibernate processing, other than that I don't know what could go on)

**Comment by tbroyer** [comment]
That would probably be the metamodel generator then, yes: http://in.relation.to/2009/11/09/hibernate-static-metamodel-generator-annotation-processor/ & http://hibernate.org/orm/tooling/ & http://docs.jboss.org/hibernate/orm/5.3/topical/html_single/metamodelgen/MetamodelGenerator.html

**Comment by wemu** [comment]
Ahhh I see. Thanks!
