### ISSUE TITLE
can't resolve processor required jar

### ISSUE THREAD

**Issue by lugreen** [tbroyer/gradle-apt-plugin#82]
Hi,
I have a processor artifact,and add the artifact using "annotationProcessor",such as:
![image](https://user-images.githubusercontent.com/1725996/40605173-0715021a-6294-11e8-88c8-ec2f9eec4fe3.png)
When compile the java file, the compiler will report some error, it means can't find som calss define. 
![image](https://user-images.githubusercontent.com/1725996/40605333-9fa6c39c-6294-11e8-9b59-a10632268afe.png)
I have to add processor required java lib manually,such as:
![image](https://user-images.githubusercontent.com/1725996/40605395-d6cc367c-6294-11e8-8c7e-69253ba6ff38.png)
May i missing some config?

Env:
Gradle:4.1
OS:Windows10
IDE: IDEA2017.2.6

**Comment by tbroyer** [comment]
Assuming you used https://github.com/lugreen/extclassgenerator-apt/blob/d75bd67f559f0dbf0204864456c12e38019887eb/cmd_deploy.bat to deploy the processor; it uses `-DgeneratePom=true` and no `-DpomFile=…` so the deployed POM does not list any dependency.

**Comment by lugreen** [comment]
Thank you very much.
