### ISSUE TITLE
Can Gradle 4.9 be used to automatically configure APT when using Buildship?

### ISSUE THREAD

**Issue by ChristianCiach** [tbroyer/gradle-apt-plugin#86]
This may be wishful thinking, but I really want to avoid executing "eclipseFactorypath", "eclipseJdtApt" and "eclipseJdt" every time when importing projects into Eclipse or when the factorypath changes. (There is no way I can convince my colleages to do this).

I've just read the [Gradle 4.9 rc-1 release notes](https://docs.gradle.org/4.9-rc-1/release-notes.html#eclipseproject-tasks-defined-for-gradle-eclipse-may-now-run-in-buildship), where it states:

> The EclipseClasspath and EclipseProject tasks both accept beforeMerged and whenMerged closures, for advanced Eclipse-specific customisation.
> 
> Previous versions of Gradle did not execute the closures defined in EclipseProject when invoked from Buildship (only those in EclipseClasspath). Now Gradle executes them both, similarly to when invoked from the command-line.

Can this be used to avoid the need to manually execute said tasks?

**Comment by tbroyer** [comment]
> Can this be used to avoid the need to manually execute said tasks?

No. Those tasks (and their closures) only deal with the `.project` and `.classpath` files; `eclipseFactorypath`, `eclipseJdt` and `eclipseJdtApt` all deal with different configuration files.

Follow https://github.com/eclipse/buildship/issues/329 and https://github.com/gradle/gradle/issues/2300 for better Buildship and Gradle integration of annotation processors.
