### ISSUE TITLE
IntelliJ-Integration after v0.10

### ISSUE THREAD

**Issue by brainbytes42** [tbroyer/gradle-apt-plugin#88]
Using gradle 3.5-rc2, I aimed at giving google's dagger2 a try. The documentation was a little oder and directed me to use 

    plugins {
      id "net.ltgt.apt" version "0.10"
    }

also using idea-plugin for IntelliJ, everything worked fine with this dependency:

	compile 'com.google.dagger:dagger:2.+'
	apt 'com.google.dagger:dagger-compiler:2.+'

But then I thougt: Let's check, if it's the current version... it was'nt, so I updated the plugin to use `0.18`.
That yielded a) a warning, "apt" would be replaced by annotationProcessor - ok, thats fine.
But b) the IntelliJ IDE (2018.2) lost track of the generated source-files and yelled "cannot resolve dependency". 

The gradle-build worked perfectly fine, while IntelliJ was complaining - so it's just the problem of setting source folders, the source was visible, but not set as source.

Changing apt to annotationProcessor worked for gradle (and removed the warning as expected), but didn't chane anything about the IntelliJ-issue.

When I changed back to plugin v `0.10` (and back to apt, as annotationProcessor wasn't known with that version), immediately the sourcefolders were recognized again, everything fine.

Changing to v. `0.11` made the whole thing fail again, v. 0.10 again: working.

But then I decided to update gradle as well, which was a little outdated. Now with gradle 4.10, the old plugin doesn't work anymore, so changing to v.0.18 and hoping the new gradle would solve something for the newer version - but it didn't. 

I have to admit, I have no idea, where the issue is - if it's this plugin (which I assume, as changing to later than 0.10 made it fail) or intellij-plugin or whatever... ? Any idea about that? Or about a possible fix in build.gradle?

I fixed it in IntelliJ specifying the proper folder as source folder, but reimporting sould make it fail again.

Thanks for anny feedback/support.

**Comment by tbroyer** [comment]
From https://github.com/tbroyer/gradle-apt-plugin/blob/v0.18/README.md#intellij-idea:
> Starting with version 0.11, applying the `net.ltgt.apt-idea` plugin will auto-configure the generated files to enable annotation processing in IntelliJ IDEA. In prior versions (until 0.10), that configuration would automatically happen whenever both the `net.ltgt.apt` and `idea` were applied (the new `net.ltgt.apt-idea` plugin will also automatically apply the `net.ltgt.apt` and `idea` plugins).

You need to add
```groovy
  id "net.ltgt.apt-idea" version "0.18"
```
to your `plugins {}` section **or** treat it as a developer-specific setting and instead add a Gradle init script that will apply `net.ltgt.apt-idea` whenever `net.ltgt.apt` is applied (see the snippet just before https://github.com/tbroyer/gradle-apt-plugin/blob/v0.18/README.md#configuration).

Fwiw, I'm personally using the latter approach.

**Comment by brainbytes42** [comment]
thank you very much, obviously I've overlooked that detail! :-)
