### ISSUE TITLE
Configure generated sources output directory

### ISSUE THREAD

**Issue by yissachar** [tbroyer/gradle-apt-plugin#9]
For various reasons, I don't want my APT generated sources to end up in the build directory, but instead in a custom directory of my choosing. Is this possible? Looking at the source, it seems that the build directory is hardcoded in.

My current work-around is to add a task that copies the files from the build directory to my own directory, but it would be nice if I could skip this step and just generate them there in the first place.

**Comment by tbroyer** [comment]
I'm afraid it's not possible, and I can't think of a (easy) way to configure the output directory (based on a global "naming rule"? expressed as pattern string with placeholder? or a closure? or maybe based on a map from sourceset name to output directory?)

Or maybe there's a way with Gradle to add a property to each `JavaCompile` class that could be given a default value and could be overridden? I'm afraid I don't know enough about Gradle internals to do that (if that's even possible).

That said, given the low complexity of the plugin, I think it'd be easier to just "fork" the plugin (it's one class with no third-party dependency, so you can just copy/paste it to your project's `buildSrc`; or you could do the same in your build script without the plugin (it's not that hard).

**Comment by yissachar** [comment]
OK, I see the issue. Not a big deal - I'll just use one of the work-arounds. Thanks for the plugin!

**Comment by tbroyer** [comment]
I might have found a way to actually do that (using Gradle _conventions_ to extend the `SourceSet` model object and the `JavaCompile` tasks)

**Comment by fab1an** [comment]
How do you do it?

**Comment by tbroyer** [comment]
Not implemented yet (done locally, not yet pushed to GitHub; needs a bit more work)

**Comment by Grimshanker** [comment]
Hi, do you know when this change might be made available or are you still suggesting the workarounds mentioned above?
Thanks for the plugin.

**Comment by tbroyer** [comment]
Should be fixed by 292861dc948ba6b37e5ff15ca079d33c3208b019

**Comment by tbroyer** [comment]
Released in v0.8, note that IntelliJ IDEA integration still (partially) uses the hard-coded `build/generated/source/apt/…` paths.
