### ISSUE TITLE
gradle-apt-plugin doesn't generate when using grale-errorprone-plugin

### ISSUE THREAD

**Issue by scottsue** [tbroyer/gradle-apt-plugin#91]
Hi,

I've just upgraded to using the latest version of both net.ltgt.apt (0.19) and net.ltgt.errorprone (0.6).

When I run my gradle build my AutoValue classes do not generate.  At the moment I am still on Java8 so I've also had to include the following as per the errorprone readme:

dependencies {
	errorproneJavac("com.google.errorprone:javac:9+181-r4173-1")
	errorprone("com.google.errorprone:error_prone_core:2.3.2")
}

When running previous versions of these two plugins there was no issues
    id "net.ltgt.apt" version "0.15"
    id "net.ltgt.errorprone" version "0.0.14"

Is there something that I'm missing here?

Thanks in advance!

**Comment by tbroyer** [comment]
Make sure your annotation processor is added to the `annotationProcessor` configuration. For AutoValue, that means adding `auto-value-annotations` to the `api` (or `compile`, `implementation`, or `compileOnly`) configuration, and `auto-value` (the processor) to the `annotationProcessor` configuration.

The difference between `net.ltgt.errorprone` 0.0.x and `net.ltgt.errorprone` 0.6 is that in 0.6 Error Prone is added to the `annotationProcessor` (and `testAnnotationProcessor`, etc.) configurations. If they were previously empty, with the compiler defaulting to the `compileClasspath` to look for annotation processors (with Gradle emitting a warning in recent versions; this fallback behavior will be removed in Gradle 5), it's no longer the case, and processors are no longer seen.

**Comment by scottsue** [comment]
Thanks Thomas, looks like I was missing the annotationProcessor as you have above.  Thanks for your help
