### ISSUE TITLE
Provide Gradle Kotlin DSL examples in documentation

### ISSUE THREAD

**Issue by eriwen** [tbroyer/gradle-apt-plugin#92]
As a [Gradle Kotlin DSL](https://github.com/gradle/kotlin-dsl) adopter, I'd like to know how to configure this plugin using the Kotlin DSL.

[This plugin was identified](https://github.com/gradle/gradle/issues/6790) as one of the most useful Gradle plugins. With Kotlin DSL 1.0 approaching shortly, it'd be wonderful if the documentation provided Kotlin and Groovy DSL samples. [Blog post with suggestions](https://blog.gradle.org/groovy-kotlin-dsl-samples).

Here are a couple additional resources:

 * [Migrating build logic from Groovy to Kotlin guide](https://guides.gradle.org/migrating-build-logic-from-groovy-to-kotlin/)
 * [Exemplar for automated samples testing](https://blog.gradle.org/documentation-samples-testing-exemplar)
 * [Join #kotlin-dsl channel in Gradle Community Slack for personalized help](https://join.slack.com/t/gradle-community/shared_invite/enQtNDE3MzAwNjkxMzY0LTYwMTk0MWUwN2FiMzIzOWM3MzBjYjMxNWYzMDE1NGIwOTJkMTQ2NDEzOGM2OWIzNmU1ZTk5MjVhYjFhMTI3MmE)

Thank you for providing a great Gradle plugin! —The Gradle Team

**Comment by tbroyer** [comment]
Ha, this is a good reminder to update the project to better support Kotlin DSL.

Incidentally, this plugin being “one of the most useful” is a clear indication that the functionality really should be built into Gradle (gradle/gradle#2300; in terms of build, everything's there already –`annotationProcessor` configurations, and `annotationProcessorGeneratedSourcesDir`–, it's the IDE support that's lacking), IntelliJ (https://youtrack.jetbrains.com/issue/IDEA-187868 & https://youtrack.jetbrains.com/issue/IDEA-182577), and Buildship (https://github.com/eclipse/buildship/issues/329)

**Comment by eriwen** [comment]
Thank you!
