### ISSUE TITLE
Custom DI not getting generated

### ISSUE THREAD

**Issue by Kavyamanjanatha** [tbroyer/gradle-apt-plugin#93]
HI

When i use the plugin , our custom DI classes are not getting generated.
E.g lets say i have custom DI  and when i  try to use the plugin for mapstruct somehow our annotation processors and apt plugin annotation processor are not working together.

Do i need to enable or disable any configurations for this.

**Comment by tbroyer** [comment]
Which version of Gradle are you using? Which version of this plugin? How are your annotation processors configured in your build script? Specifically, did you add them to the `annotationProcessor` configuration? (see https://github.com/tbroyer/gradle-apt-plugin/blob/648bf2810097799796fdeb327255cdc99733aabd/README.md#example-usage)

**Comment by Kavyamanjanatha** [comment]
Hi tbroyer
Thanks for your quick reply.
i understood that issue  is with our build script & i am trying to fix it.Meanwhile can we configure different path for the generated classes. Currently the files are generated under build->source->apt. (Can w e configure different path)

**Comment by tbroyer** [comment]
⇒ https://github.com/tbroyer/gradle-apt-plugin/blob/648bf2810097799796fdeb327255cdc99733aabd/README.md#configuration, i.e. configure `options.annotationProcessorGeneratedSourcesDirectory` (native Gradle property) of your compile task.
