### ISSUE TITLE
apt-eclipse plugin can cause deprecation warnings on Gradle 5.1

### ISSUE THREAD

**Issue by shollander** [tbroyer/gradle-apt-plugin#94]
Given the following in a `build.gradle` file with the apt-eclipse plugin applied:
```
buildscript {
    ext {
        myStuff = [
            [someName: "value1"],
            [someName: "value2"]
        ]
    }
}
```

A deprecation warning with the following stacktrace is created by Gradle (only when the `net.ltgt.apt-eclipse` plugin is applied). (Run `gradle help --warning-mode all --stackrace` to show.)

```
Using method ObjectFactory.property() method to create a property of type Map<K, V> has been deprecated. This wil fail with an error in Gradle 6.0. Please use ObjectFactory.mapProperty() instead.
    at org.gradle.api.internal.model.DefaultObjectFactory.property(DefaultObjectFactory.java:111)
    at net.ltgt.gradle.apt.EclipseJdtApt.<init>(EclipseJdpApt.java:46)
    at net.ltgt.gradle.apt.EclipseJdtApt_Decorated.<init>(Unknown Source)
```

This only started occuring with version 0.20. I can use 0.19 without a problem.

**Comment by tbroyer** [comment]
Thanks for the report. Fwiw, this would only happen in 5.1+, not 5.0, but yes, I'll fix that.
