### ISSUE TITLE
Property to change "Generated test source directory"

### ISSUE THREAD

**Issue by jmeierhofer** [tbroyer/gradle-apt-plugin#95]
Hello,

is it possible to change the Eclipse configuration where the "Generated test source directory" is?
Eclipse generates a folder with the name ".apt_generated_tests" in the project's directory.

I know there is a property in the net.ltgt.gradle.apt.EclipseJdtApt with name "genSrcDir" which I changed to another directory. Is there a chance to do this also for the ".apt_generated_tests"?

![grafik](https://user-images.githubusercontent.com/46316621/51610542-498cfd00-1f1d-11e9-90e8-d5bebf86eadf.png)

Regards
jmeierhofer

**Comment by tbroyer** [comment]
Oh wow, this is news to me! For years Eclipse only had a single output directory for both main and test, and I'm not an Eclipse user so…

Could you tell me the configuration key in `.settings/org.eclipse.jdt.apt.core.prefs` for that other directory? (single output dir used to be `org.eclipse.jdt.apt.genSrcDir`)

Also, as you're at it, which other keys are there in this file? Currently, the plugin will generate:
```properties
org.eclipse.jdt.apt.aptEnabled=true
org.eclipse.jdt.apt.genSrcDir=.apt_generated
org.eclipse.jdt.apt.reconcileEnabled=true
```
(and `org.eclipse.jdt.core.compiler.processAnnotations=true` in `.settings/org.eclipse.jdt.core.prefs`).
IIRC, `aptEnabled` is obsolete (replaced by `processAnnotations`), and `reconcileEnabled` corresponds to _Enable processing in editor_.

**Comment by jmeierhofer** [comment]
Had to rename the test src dir, to see the changes in the org.eclipse.jdt.apt.core.prefs file
The content is:
`
eclipse.preferences.version=1
org.eclipse.jdt.apt.aptEnabled=true
org.eclipse.jdt.apt.genSrcDir=bin\\.apt_generated
org.eclipse.jdt.apt.genTestSrcDir=.apt_generated_tests2
org.eclipse.jdt.apt.reconcileEnabled=false
`

**Comment by jmeierhofer** [comment]
There is of course a new line after the version property, but somehow the format got corrupted. Sorry for that.

**Comment by jmeierhofer** [comment]
Eclipse version I use is 2018-12 with Buildship 3.0.1

**Comment by tbroyer** [comment]
Thanks, will add this (possibly not before this weekend though, and I have no idea when I'll cut the next release)

**Comment by jmeierhofer** [comment]
Thank you very much. Hope you will release soon ;-)

**Comment by tbroyer** [comment]
Pending v0.21, you should be able to configure it from the build using something like:
```gradle
eclipse {
  jdt {
    apt {
      withProperties { properties ->
        properties["org.eclipse.jdt.apt.genTestSrcDir"] = project.file("bin/.apt_generated_tests")
      }
    }
  }
}
```
