### ISSUE TITLE
Invalid Idea config prevents from editing project structure

### ISSUE THREAD

**Issue by jmattheis** [tbroyer/gradle-apt-plugin#96]
With a recent update of Intellij Ultimate (something between 2018.2 and 2018.3.5) the plugin now generates an invalid config. The plugin adds the apt generated sources path to both source folders and generated source folders.
<details>
<summary>Image</summary>

![image](https://user-images.githubusercontent.com/14895212/54762290-1a7cca00-4bf4-11e9-9142-34146ce6a3ef.png)
</details>

Idea doesn't compain about this until you edit something in the project structure. F.ex editing the output path inside `Paths`.

<details>
<summary>Image</summary>

![image](https://user-images.githubusercontent.com/14895212/54762392-53b53a00-4bf4-11e9-9491-aa1029f48394.png)
</details>

The error message is:
> Source root "path to apt generated source main" is duplicated in module "my module"

We need to edit one of the Entries in Facets (related to GWT). These values are kept after a Gradle refresh inside Intellij.

Do you have an idea how we can fix this problem?

Config:
```
plugins {
    id 'java'
    id 'net.ltgt.apt' version "0.21"
}

group 'test'
version '1.0-SNAPSHOT'

apply plugin: "java"
apply plugin: "maven"
apply plugin: 'net.ltgt.apt-idea'
sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
}
```
Using Gradle 4.10.2 but also occurs with version 5.2.

**Comment by tbroyer** [comment]
My recommendation is to stop using this plugin: https://github.com/tbroyer/gradle-apt-plugin/blob/master/README.md#do-without-the-plugin

**Comment by jmattheis** [comment]
Oke.
